name: handshake-haven-crm
services:
- name: web
  source_dir: /
  github:
    repo: your-username/handshake-haven-crm
    branch: main
    deploy_on_push: true
  build_command: npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  health_check:
    http_path: /api/health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 3
    success_threshold: 1
  envs:
  - key: NODE_ENV
    value: production
  - key: POSTGRESQL_URI
    value: ${handshake-haven-db.DATABASE_URL}
  - key: PORT
    value: "5000"

databases:
- name: handshake-haven-db
  engine: PG
  version: "15"
  size: db-s-dev-database 